<x-layouts.app title="{{ $item->name }} — Estoque">
<div class="flex flex-wrap gap-3 mb-5"><a class="arena-btn-secondary" href="{{ route('store.index') }}">Voltar ao estoque</a><a class="arena-btn-secondary" href="{{ route('store.edit',$item) }}">Editar produto</a></div>
<header class="arena-card p-6"><p class="eyebrow">{{ $item->sku }} · {{ $item->game }}</p><h1 class="text-3xl font-bold mt-2">{{ $item->name }}</h1><p class="text-slate-400 mt-2">{{ $item->edition }} · {{ $item->condition }} · {{ $item->rarity }}</p><div class="grid gap-5 sm:grid-cols-3 mt-6"><div><p class="text-slate-400">Saldo atual</p><p class="text-4xl font-bold">{{ $item->quantity }}</p>@if($item->quantity<=$item->minimum_quantity)<p class="text-amber-200">Estoque baixo · mínimo {{ $item->minimum_quantity }}</p>@endif</div><div><p class="text-slate-400">Custo unitário · privado</p><p class="text-2xl font-bold">R$ {{ number_format($item->cost,2,',','.') }}</p></div><div><p class="text-slate-400">Preço de venda</p><p class="text-2xl font-bold">R$ {{ number_format($item->price,2,',','.') }}</p></div></div></header>
<div class="grid gap-5 lg:grid-cols-2 mt-5">
<section class="arena-card p-6"><h2 class="text-xl font-bold mb-4">Movimentar estoque</h2>
@if($item->archived)<p class="text-slate-400">Produto arquivado. Reative para registrar movimentações.</p>@else
<form method="POST" action="{{ route('store.move',$item) }}" class="grid gap-4" x-data="{sending:false}" @submit="sending=true">@csrf<input type="hidden" name="request_id" value="{{ old('request_id',(string)Illuminate\Support\Str::uuid()) }}">
<label class="arena-label">Operação<select class="arena-input mt-2" name="direction"><option value="in" @selected(old('direction')==='in')>Entrada</option><option value="out" @selected(old('direction')==='out')>Saída</option></select></label>
<label class="arena-label">Quantidade<input class="arena-input mt-2" type="number" name="quantity" min="1" max="999999" value="{{ old('quantity',1) }}" required></label>
<label class="arena-label">Motivo<input class="arena-input mt-2" name="reason" maxlength="255" value="{{ old('reason') }}" placeholder="Ex.: compra, venda confirmada, avaria ou correção" required></label>
<button class="arena-btn" :disabled="sending">Registrar movimentação</button></form>@endif
</section>
<section class="arena-card p-6"><h2 class="text-xl font-bold">Disponibilidade</h2><p class="mt-3 text-slate-300">{{ $item->archived ? 'Produto arquivado.' : ($item->published ? ($item->quantity>0?'Publicado no marketplace.':'Anúncio indisponível por falta de estoque.') : 'Anúncio pausado; produto privado.') }}</p><p class="text-sm text-slate-400 mt-3">Um anúncio publicado some quando o saldo zera e reaparece quando você repõe o estoque. Pause para impedir a republicação automática.</p>
<form method="POST" action="{{ route('store.publish',$item) }}" class="mt-5">@csrf @method('PATCH')<input type="hidden" name="published" value="{{ $item->published ? 0:1 }}"><button class="arena-btn-secondary" @disabled(!$item->published && ($item->archived || !$item->quantity))>{{ $item->published ? 'Pausar anúncio' : 'Publicar no marketplace' }}</button></form>
@if($item->listing)<a class="underline block mt-4" href="{{ route('marketplace.show',$item->listing) }}">Ver anúncio</a>@endif
<form method="POST" action="{{ route('store.archive',$item) }}" class="mt-6">@csrf @method('PATCH')<input type="hidden" name="archived" value="{{ $item->archived ? 0:1 }}"><button class="arena-btn-secondary" @disabled(!$item->archived && $item->quantity>0)>{{ $item->archived ? 'Reativar produto' : 'Arquivar produto sem saldo' }}</button></form><p class="text-xs text-slate-400 mt-3">Arquivar preserva o histórico e pausa o anúncio.</p>
</section></div>
<section class="arena-card p-6 mt-5"><h2 class="text-xl font-bold mb-4">Histórico de movimentações</h2><div class="overflow-x-auto"><table class="w-full text-sm text-left"><thead><tr class="text-slate-400"><th class="p-3">Data (Brasília)</th><th class="p-3">Alteração</th><th class="p-3">Saldo</th><th class="p-3">Motivo</th><th class="p-3">Responsável</th></tr></thead><tbody>@forelse($movements as $move)<tr class="border-t border-white/10"><td class="p-3 whitespace-nowrap">{{ $move->created_at->timezone('America/Sao_Paulo')->format('d/m/Y H:i') }}</td><td class="p-3 {{ $move->delta>0?'text-emerald-300':'text-amber-200' }}">{{ $move->delta>0?'+':'' }}{{ $move->delta }}</td><td class="p-3 whitespace-nowrap">{{ $move->before_quantity }} → {{ $move->after_quantity }}</td><td class="p-3">{{ $move->reason }}</td><td class="p-3">{{ $move->user->name }}</td></tr>@empty<tr><td colspan="5" class="p-5 text-slate-400">Nenhuma movimentação. O produto foi cadastrado sem saldo.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $movements->links() }}</div><p class="text-xs text-slate-400 mt-4">Movimentações não são apagadas. Corrija um lançamento com uma nova entrada ou saída e informe o motivo.</p></section>
</x-layouts.app>
